### ISSUE TITLE
Meetup todo list

### ISSUE THREAD

**Issue by vasarhelyia** [NSBudapest/NSBudapestMeetup#1]
This month is organized by: **@[github name]**
- [ ] get a venue (make sure they offer snacks, drinks, seats limit)
- [ ] get speakers
- [ ] make the speakers to drop an issue
- [ ] find a date (please at least make a search on meetup.com for that date
- [ ] create the meetup event, meetup link: 
- [ ] announce it
- [ ] announce it on twitter also
- [ ] organize rehearsal
- [ ] one week before it send an email to update their RSVP
- [ ] one week before it tweet about it to update their RSVP
- [ ] make rehearsal happen
- [ ] book a bar
- [ ] one day before it send an email
- [ ] one day before it tweet about
- [ ] tweet on meetup's day
- [ ] tweet during the meetup with photos about the talks/speakers
- [ ] during the breaks (or between talks) put the conferences section on the projector
- [ ] thank you tweet next day
- [ ] collect talks/slides/codes and put on the website and the README
